version: '3.8'

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'

  mongo-express:
    image: 'mongo-express:latest'
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=secret'
    ports:
      - '8081'
    depends_on:
      - mongodb