name: Versionamento automatico

on:
  push:
    branches:
      - main

# Add this permissions block
permissions:
  contents: write

jobs:
  versionamento:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante per avere la storia completa dei tag

      - name: Configura Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Recupera i tag remoti
        run: git fetch --tags

      - name: Genera la nuova versione
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            NEW_TAG="v1.0.0"
          else
            # Incrementa la versione minor
            NEW_TAG=$(echo $LATEST_TAG | awk -F. '{$NF++; print $1"."$2"."$3}' OFS='.')
          fi
          echo "Nuova versione: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          git tag $NEW_TAG

      - name: Push nuovo tag su GitHub
        run: git push origin ${{ env.NEW_TAG }}