name: Versionamento automatico

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Necessario per pushare tag

jobs:
  versionamento:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessario per accedere alla cronologia completa dei tag

      - name: Configura Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Recupera i tag remoti
        run: git fetch --tags

      - name: Genera la nuova versione
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          if [[ "$LATEST_TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=${BASH_REMATCH[3]}
            PATCH=$((PATCH + 1))
            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          else
            NEW_TAG="v1.0.0"
          fi
          echo "Nuova versione: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          git tag $NEW_TAG

      - name: Push nuovo tag su GitHub
        run: git push origin ${{ env.NEW_TAG }}
